CREATE TABLE RM_ACCOUNT (
       ACCOUNT_ID INT(11) NOT NULL AUTO_INCREMENT
   , MONEY_ACCOUNT_ID VARCHAR(100) NOT NULL
    , ACCOUNT_TYPE_ID INT(50) NOT NULL
    , MONEY_ACCOUNT_BALANCE DECIMAL(19,4) NOT NULL DEFAULT '0.00'
   , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
    , CONSTRAINT RM_ACCOUNT_FK1 FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES RM_ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);