CREATE TABLE RM_TRANSACTION_TYPE (
     TRANSACTION_TYPE_CODE CHAR(1) NOT NULL
    , TRANSACTION_TYPE_CODE_DESC VARCHAR(100) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_TRANSACTION_TYPE_PK PRIMARY KEY (TRANSACTION_TYPE_CODE)
);