CREATE TABLE RT_TRANSACTION (
     TRANSACTION_ID INT(11) NOT NULL AUTO_INCREMENT
    , TRANSACTION_UNIQUE_ID VARCHAR(100) NOT NULL
    , TRANSACTION_TYPE_CODE CHAR(1) NOT NULL
    , TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , TRANSACTION_AMOUNT DECIMAL(19,4) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID)
    , CONSTRAINT RT_TRANSACTION_FK1 FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE)
);