CREATE TABLE RT_TRANSACTION_LEDGER (
    TRANSACTION_LEDGER_ID INT(11) NOT NULL AUTO_INCREMENT
    , TRANSACTION_ID INT(11) NOT NULL
    , ACCOUNT_ID INT(11) NOT NULL
    , LEDGER_TYPE_CODE CHAR(1) NOT NULL 
    , LEDGER_TRANSACTION_AMOUNT DECIMAL(19,4) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_TRANSACTION_LEDGER_PK PRIMARY KEY (TRANSACTION_LEDGER_ID)
    , CONSTRAINT RT_TRANSACTION_LEDGER_FK1 FOREIGN KEY (TRANSACTION_ID) REFERENCES RT_TRANSACTION(TRANSACTION_ID)
    , CONSTRAINT RT_TRANSACTION_LEDGER_FK2 FOREIGN KEY (ACCOUNT_ID) REFERENCES RM_ACCOUNT(ACCOUNT_ID)
);