version: '3.7'

services:
  db:
    container_name: "rpaydb"
    image: mariadb
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    environment:
      - GET_HOSTS_FROM=dns
    # setting some env vars to create the DB
    environment:
      MARIADB_ROOT_PASSWORD: "Team@1000"
      MARIADB_DATABASE: "rpay"
      MARIADB_USER: "anirudh"
      MARIADB_PASSWORD: "Team@1000"
    volumes:
      - .:/app/
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "rpay"
    image : anirudhteam/rpayapi:latest
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - GET_HOSTS_FROM=dns
    ports:
      - "8080:8080"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/
    labels:
      kompose.service.type: LoadBalancer

