CREATE TABLE RM_USER_INFO (
   USER_INFO_ID INT(11) NOT NULL AUTO_INCREMENT
    , USER_LOGIN_ID VARCHAR(50) NOT NULL
    , FIRST_NAME VARCHAR(100) NOT NULL
    , MIDDLE_NAME VARCHAR(100) NOT NULL
    , LAST_NAME VARCHAR(100) NOT NULL
    , USER_PHONE INT(10) NOT NULL
    , USER_PHONE_VERIFIED tinyint(1) NOT NULL DEFAULT 0
    , USER_EMAIL VARCHAR(200) NOT NULL
    , USER_EMAIL_VERIFIED tinyint(1) NOT NULL DEFAULT 0
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_USER_INFO_PK PRIMARY KEY (USER_INFO_ID)
);