CREATE TABLE RM_ACCOUNT_TYPE (
   ACCOUNT_TYPE_ID INT(50) NOT NULL
   , ACCOUNT_TYPE_DESC VARCHAR(100) NOT NULL
   , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_ACCOUNT_TYPE_PK PRIMARY KEY (ACCOUNT_TYPE_ID)
);