CREATE TABLE RM_USER_ACCOUNT (
    USER_ACCOUNT_ID INT(11) NOT NULL AUTO_INCREMENT
   , USER_INFO_ID INT(11) NOT NULL
    , ACCOUNT_ID INT(11) NOT NULL
   , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_USER_ACCOUNT_PK PRIMARY KEY (USER_ACCOUNT_ID)
    , CONSTRAINT RM_USER_ACCOUNT_FK1 FOREIGN KEY (USER_INFO_ID) REFERENCES RM_USER_INFO (USER_INFO_ID)
    , CONSTRAINT RM_USER_ACCOUNT_FK2 FOREIGN KEY (ACCOUNT_ID) REFERENCES RM_ACCOUNT (ACCOUNT_ID)
);