INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY)
values (0,"CASH",'Admin','Admin');
INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY) 
values (1,"RAKUTEN_POINTS",'Admin','Admin');
INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY) 
values (2,"CASH_BACK",'Admin','Admin');
INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY)
values (3,"DDA",'Admin','Admin');
INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY) 
values (4,"PREPAID",'Admin','Admin');
INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY) 
values (5,"PAYLATER",'Admin','Admin');

-- Creating Users Anirudh Rakshith
INSERT into RM_USER_INFO(USER_LOGIN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,USER_PHONE,USER_PHONE_VERIFIED,USER_EMAIL,USER_EMAIL_VERIFIED,IS_ACTIVE,IS_BLACKLISTED,CREATED_BY,UPDATED_BY)
VALUES('anirudh123','Anirudh',' ','G',1234567890,1,'anirudh@rakuten.com',1,1,0,'Admin','Admin');
INSERT into RM_USER_INFO(USER_LOGIN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,USER_PHONE,USER_PHONE_VERIFIED,USER_EMAIL,USER_EMAIL_VERIFIED,IS_ACTIVE,IS_BLACKLISTED,CREATED_BY,UPDATED_BY)
VALUES('rakshit123','Rakshit',' ','K',187654321,1,'rakshit@rakuten.com',1,1,0,'Admin','Admin');

-- Anirudh's wallet, Rakuten Points, Cash Back accounts
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('cash_acc01',0,10000,543,TRUE,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('rpoints_acc01',1,100,-1,TRUE,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('cb_acc01',2,10,-1,True,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('pre_acc01',4,10,-1,True,'Admin','Admin');

-- Rakshit's wallet, Rakuten Points, Cash Back accounts
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('cash_acc02',0,10000,543,1,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('rpoints_acc02',1,100,-1,1,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,SECURITY_CODE,IS_ACTIVE,CREATED_BY,UPDATED_BY)
VALUES('cb_acc02',2,10,-1,1,'Admin','Admin');

-- mapping respective accounts to user Anirudh
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(1,1,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(1,2,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(1,3,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(1,4,'Admin','Admin');

-- mapping respective accounts to user Rakshit
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(2,5,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(2,6,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(2,7,'Admin','Admin');


INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('a','DEPOSIT','Admin','Admin');
INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('b','TRANSFER','Admin','Admin');
INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('c','WITHDRAWAL','Admin','Admin');