-- Transfer amount 100 from Rakshith account to Anirudh
INSERT INTO RT_TRANSACTION(TRANSACTION_UNIQUE_ID,TRANSACTION_TYPE_CODE,TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
values('T1','b','100','Admin','Admin');

INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
values (1,4,'D',-100,'Admin','Admin');
INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
values (1,1,'C',+100,'Admin','Admin');

UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE+100 where MONEY_ACCOUNT_ID='cash_acc01' ;
UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE-100 where MONEY_ACCOUNT_ID='cash_acc02' ;


-- -- Redeem 100 Rakuten Points ( which is 10 doller equivalent ) into wallet
-- INSERT INTO RT_TRANSACTION(TRANSACTION_UNIQUE_ID,TRANSACTION_TYPE_CODE,TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values('T2','c','10','Admin','Admin');

-- INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values (2,2,'D',-10,'Admin','Admin');
-- INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values (2,1,'C',+10,'Admin','Admin');

-- UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE+10 where MONEY_ACCOUNT_ID='cash_acc01' ;
-- UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE-100 where MONEY_ACCOUNT_ID='rpoints_acc01' ;

-- -- Redeem 10 Cash Back into wallet
-- INSERT INTO RT_TRANSACTION(TRANSACTION_UNIQUE_ID,TRANSACTION_TYPE_CODE,TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values('T3','c','10','Admin','Admin');

-- INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values (3,3,'D',-10,'Admin','Admin');
-- INSERT INTO RT_TRANSACTION_LEDGER(TRANSACTION_ID,ACCOUNT_ID,LEDGER_TYPE_CODE,LEDGER_TRANSACTION_AMOUNT,CREATED_BY,UPDATED_BY)
-- values (3,1,'C',+10,'Admin','Admin');

-- UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE+10 where MONEY_ACCOUNT_ID='cash_acc01' ;
-- -- UPDATE RM_ACCOUNT set MONEY_ACCOUNT_BALANCE = MONEY_ACCOUNT_BALANCE-10 where MONEY_ACCOUNT_ID='cb_acc01' ;
